services:
  frontend:
    build: ../frontend # Ajustez le chemin vers votre dossier client web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - supfile-network

  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - supfile-network
    volumes:
      - uploads_data:/usr/src/app/uploads

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-supfile_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d supfile_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - supfile-network

networks:
  supfile-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: